decentraland/agora

webapp/src/modules/vote/sagas.ts
=> feat: sign all data on vote

webapp/src/modules/vote/sagas.ts
=> feat: sign poll description

src/Translation/locales/en.json, src/Translation/locales/es.json, webapp/src/components/PollDetailPage/PollDetailPage.tsx, webapp/src/components/PollsPage/PollsPage.tsx
=> feat: remove submitter and partial results cols

webapp/src/components/OptionBar/OptionBar.css, webapp/src/components/OptionBar/OptionBar.tsx, webapp/src/components/OptionBar/index.ts, webapp/src/components/OptionBar/types.ts, webapp/src/components/PollDetailPage/PollDetailPage.css, webapp/src/components/PollDetailPage/PollDetailPage.tsx
=> feat: mobile percentage bars

webapp/src/components/PollDetailPage/PollDetailPage.tsx
=> fix: remove token section from district polls

src/Translation/locales/en.json, src/Translation/locales/es.json, webapp/src/components/PollDetailPage/PollDetailPage.tsx, webapp/src/components/PollProgress/PollProgress.tsx, webapp/src/components/PollsPage/PollsPage.tsx, webapp/src/modules/poll/utils.ts
Splits homepage polls into District Plan Acceptance and Decentraland Polls
Closes #51
=> feat: split homepage polls

src/Translation/locales/en.json, src/Translation/locales/es.json, webapp/src/components/PollDetailPage/PollDetailPage.tsx, webapp/src/lib/utils.ts
=> feat: show finished polls

webapp/src/components/PollsPage/PollsPage.css
=> fix: polls page margins

package-lock.json, package.json, webapp/src/components/PollDetailPage/PollDetailPage.tsx, webapp/src/modules.d.ts
via `react-linkify`
Closes: #53
=> feat: made links clickable

package-lock.json, package.json, webapp/package-lock.json, webapp/package.json, webapp/src/components/PollDetailPage/PollDetailPage.css, webapp/src/components/PollDetailPage/PollDetailPage.tsx, webapp/src/components/PollProgress/PollProgress.css, webapp/src/components/PollsPage/PollsPage.tsx, webapp/src/components/VotePage/VotePage.tsx
Closes #63 
Closes #64 
Closes #65
=> fix: several things

webapp/src/components/PollDetailPage/PollDetailPage.tsx
=> fix: sort options alphabetically

src/Translation/locales/en.json, src/Translation/locales/es.json, webapp/src/components/PollDetailPage/PollDetailPage.css, webapp/src/components/PollDetailPage/PollDetailPage.tsx, webapp/src/components/PollDetailPage/types.ts, webapp/src/components/PollsPage/PollsPage.tsx, webapp/src/components/VotePage/VotePage.tsx, webapp/src/lib/utils.ts
=> feat: pagination

webapp/src/index.css, webapp/src/modules/vote/sagas.ts
This PR removes the TEST banner and TEST version from the signature. 
Merge this before releasing to Prod.
=> [MERGE RIGHT BEFORE RELEASE] chore: remove test banner and signature

webapp/package-lock.json, webapp/package.json
Better styles for Tables, fixed Blockie's colors
=> chore: bump decentraland-ui

webapp/src/components/PollDetailPage/PollDetailPage.tsx, webapp/src/components/PollProgress/PollProgress.tsx, webapp/src/components/PollsPage/PollsPage.tsx, webapp/src/modules/poll/utils.ts
a few refactors
closes #82 
closes #79
=> chore: reuse helper. remove log

webapp/package-lock.json, webapp/package.json, webapp/src/components/OptionOrb/OptionOrb.css, webapp/src/components/PollDetailPage/PollDetailPage.css, webapp/src/components/PollProgress/PollProgress.css, webapp/src/components/VotePage/VotePage.css
bump `decentraland-ui` and use css variables
=> chore: bump decentraland-ui + use css variables

src/Poll/Poll.model.ts, src/Poll/Poll.queries.ts, src/lib/Model.queries.ts, webapp/src/components/PollDetailPage/PollDetailPage.tsx, webapp/src/components/PollsPage/PollsPage.tsx, webapp/src/components/VotePage/VotePage.tsx
=> Sort options & votes in the backend

webapp/package-lock.json, webapp/package.json, webapp/src/components/Navbar/Navbar.container.tsx, webapp/src/components/Token/Token.tsx
Use props from `decentraland-ui`
=> chore: use props from decentraland-ui

webapp/package.json, webapp/src/components/Page/Page.container.ts, webapp/src/components/Page/Page.tsx, webapp/src/components/Page/Page.types.ts, webapp/src/components/Page/types.ts, webapp/src/components/PollDetailPage/CastYourVote/CastYourVote.tsx, webapp/src/components/PollDetailPage/CastYourVote/CastYourVote.types.ts, webapp/src/components/PollDetailPage/OptionBar/OptionBar.tsx, webapp/src/components/PollDetailPage/OptionBar/OptionBar.types.ts, webapp/src/components/PollDetailPage/OptionOrb/OptionOrb.tsx, webapp/src/components/PollDetailPage/OptionOrb/OptionOrb.types.ts, webapp/src/components/PollDetailPage/OptionOrb/types.ts, webapp/src/components/PollDetailPage/PollDetailPage.container.ts, webapp/src/components/PollDetailPage/PollDetailPage.tsx, webapp/src/components/PollDetailPage/PollDetailPage.types.ts, webapp/src/components/PollDetailPage/PollProgress/PollOption/PollOption.tsx, webapp/src/components/PollDetailPage/PollProgress/PollOption/PollOptions.types.ts, webapp/src/components/PollDetailPage/PollProgress/PollOption/index.ts, webapp/src/components/PollDetailPage/PollProgress/PollProgress.tsx, webapp/src/components/PollDetailPage/PollProgress/PollProgress.types.ts, webapp/src/components/PollDetailPage/YourVote/YourVote.tsx, webapp/src/components/PollDetailPage/YourVote/YourVote.types.ts, webapp/src/components/Token/Token.tsx, webapp/src/components/Token/Token.types.ts, webapp/src/components/VotePage/VotePage.container.ts, webapp/src/components/VotePage/VotePage.tsx, webapp/src/components/VotePage/VotePage.types.ts
Refactored typings to comply with standards
=> chore: standards

src/Translation/locales/en.json, src/Translation/locales/es.json, webapp/src/components/PollDetailPage/PollDetailPage.css, webapp/src/components/PollDetailPage/PollDetailPage.tsx
=> feat: add sign in message

webapp/package-lock.json, webapp/package.json
=> feat: new logo

package-lock.json, src/Translation/locales/en.json, src/Translation/locales/es.json, src/Translation/locales/fr.json, src/Translation/locales/ja.json, src/Translation/locales/ko.json, src/Translation/locales/zh.json, webapp/package-lock.json, webapp/src/components/PollDetailPage/CastYourVote/CastYourVote.tsx, webapp/src/components/PollDetailPage/PollDetailPage.tsx, webapp/src/components/VotePage/VotePage.tsx
fix: vote page and finished poll styles as requested by mat
=> fix: vote page
